openapi: 3.1.0

info:
  title: DDBJ Repository API
  version: 1.0.0

servers:
  - url: https://repository.ddbj.nig.ac.jp/api
  - url: https://repository-staging.ddbj.nig.ac.jp/api
  - url: https://repository-dev.ddbj.nig.ac.jp/api

paths:
  /validations/bioproject/via-file:
    post:
      tags:
        - Validation

      requestBody:
        $ref: '#/components/requestBodies/BioProjectViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /submissions/bioproject/via-file:
    post:
      tags:
        - Submission

      requestBody:
        $ref: '#/components/requestBodies/BioProjectViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /validations/biosample/via-file:
    post:
      tags:
        - Validation

      requestBody:
        $ref: '#/components/requestBodies/BioSampleViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /submissions/biosample/via-file:
    post:
      tags:
        - Submission

      requestBody:
        $ref: '#/components/requestBodies/BioSampleViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /validations/trad/via-file:
    post:
      tags:
        - Validation

      requestBody:
        $ref: '#/components/requestBodies/TradViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /submissions/trad/via-file:
    post:
      tags:
        - Submission

      requestBody:
        $ref: '#/components/requestBodies/TradViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /validations/dra/via-file:
    post:
      tags:
        - Validation

      requestBody:
        $ref: '#/components/requestBodies/DRAViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /submissions/dra/via-file:
    post:
      tags:
        - Submission

      requestBody:
        $ref: '#/components/requestBodies/DRAViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /validations/gea/via-file:
    post:
      tags:
        - Validation

      requestBody:
        $ref: '#/components/requestBodies/GEAViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /submissions/gea/via-file:
    post:
      tags:
        - Submission

      requestBody:
        $ref: '#/components/requestBodies/GEAViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /validations/metabobank/via-file:
    post:
      tags:
        - Validation

      requestBody:
        $ref: '#/components/requestBodies/MetaboBankViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /submissions/metabobank/via-file:
    post:
      tags:
        - Submission

      requestBody:
        $ref: '#/components/requestBodies/MetaboBankViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /validations/jvar/via-file:
    post:
      tags:
        - Validation

      requestBody:
        $ref: '#/components/requestBodies/JVarViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /submissions/jvar/via-file:
    post:
      tags:
        - Submission

      requestBody:
        $ref: '#/components/requestBodies/JVarViaFile'

      responses:
        '201':
          $ref: '#/components/responses/CreateResponseCreated'

        '400':
          $ref: '#/components/responses/CreateResponseBadRequest'

  /requests/{id}:
    get:
      tags:
        - Request

      parameters:
        - name: id
          in: path
          required: true

          schema:
            type: integer

          example: 42

      responses:
        '200':
          description: Return the request resource.

          content:
            application/json:
              schema:
                type: object

                properties:
                  status:
                    type: string

                    enum:
                      - waiting
                      - processing
                      - finished

                  validity:
                    type:
                      - string
                      - 'null'

                    enum:
                      - valid
                      - invalid
                      - error
                      - null

                  validation_reports:
                    type: object

                    properties:
                      _base:
                        $ref: '#/components/schemas/ValidationReport'

                      BioProject:
                        $ref: '#/components/schemas/ValidationReport'

                      BioSample:
                        $ref: '#/components/schemas/ValidationReport'

                      Sequence:
                        $ref: '#/components/schemas/ValidationReport'

                      Annotation:
                        $ref: '#/components/schemas/ValidationReport'

                      Submission:
                        $ref: '#/components/schemas/ValidationReport'

                      Experiment:
                        $ref: '#/components/schemas/ValidationReport'

                      Run:
                        $ref: '#/components/schemas/ValidationReport'

                      RunFile:
                        $ref: '#/components/schemas/ValidationReport'

                      Analysis:
                        $ref: '#/components/schemas/ValidationReport'

                      AnalysisFile:
                        $ref: '#/components/schemas/ValidationReport'

                      IDF:
                        $ref: '#/components/schemas/ValidationReport'

                      SDRF:
                        $ref: '#/components/schemas/ValidationReport'

                      ADF:
                        $ref: '#/components/schemas/ValidationReport'

                      RawDataFile:
                        $ref: '#/components/schemas/ValidationReport'

                      ProcessedDataFile:
                        $ref: '#/components/schemas/ValidationReport'

                      MAF:
                        $ref: '#/components/schemas/ValidationReport'

                      Study:
                        $ref: '#/components/schemas/ValidationReport'

                      SampleSet:
                        $ref: '#/components/schemas/ValidationReport'

                      Sample:
                        $ref: '#/components/schemas/ValidationReport'

                      Assay:
                        $ref: '#/components/schemas/ValidationReport'

                      VariantCallSV:
                        $ref: '#/components/schemas/ValidationReport'

                      VariantRegionSV:
                        $ref: '#/components/schemas/ValidationReport'

                      VariantCallFile:
                        $ref: '#/components/schemas/ValidationReport'

                    required:
                      - _base

                  submission:
                    type:
                      - object
                      - 'null'

                    properties:
                      id:
                        type: string

                    required:
                      - id

                required:
                  - status
                  - validity
                  - validation_reports
                  - submission

              example:
                status: finished
                validity: valid

                validation_reports:
                  - object_id: _base
                    path: null
                    validity: null
                    details: null

                  - object_id: BioSample
                    path: mybiosample.xml
                    validity: valid

                    details:
                      validity: true
                      answer: 42

                submission:
                  id: X-84

components:
  schemas:
    ValidationReport:
      type: object

      properties:
        object_id:
          type: string

          enum:
            - _base
            - BioProject
            - BioSample
            - Sequence
            - Annotation
            - Submission
            - Experiment
            - Run
            - RunFile
            - Analysis
            - AnalysisFile
            - IDF
            - SDRF
            - ADF
            - RawDataFile
            - ProcessedDataFile
            - MAF
            - Study
            - SampleSet
            - Sample
            - Assay
            - VariantCallSV
            - VariantRegionSV
            - VariantCallFile

        path:
          type:
            - string
            - 'null'

        validity:
          type:
            - string
            - 'null'

          enum:
            - valid
            - invalid
            - error
            - null

        details:
          type:
            - object
            - 'null'

      required:
        - object_id
        - path
        - validity
        - details

    BioProjectViaFileJSON:
      type: object

      properties:
        BioProject:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

      required:
        - BioProject

    BioProjectViaFileFormDataBioProject:
      allOf:
        - oneOf:
          - type: object

            properties:
              BioProject[file]:
                type: string
                format: binary

            required:
              - BioProject[file]

          - type: object

            properties:
              BioProject[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - BioProject[path]

        - type: object

          properties:
            BioProject[destination]:
              type: string

    BioSampleViaFileJSON:
      type: object

      properties:
        BioSample:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

      required:
        - BioSample

    BioSampleViaFileFormDataBioSample:
      allOf:
        - oneOf:
          - type: object

            properties:
              BioSample[file]:
                type: string
                format: binary

            required:
              - BioSample[file]

          - type: object

            properties:
              BioSample[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - BioSample[path]

        - type: object

          properties:
            BioSample[destination]:
              type: string

    TradViaFileJSON:
      type: object

      properties:
        Sequence:
          type: array
          minItems: 1

          items:
            type: object

            properties:
              path:
                $ref: '#/components/schemas/UserHomePath'

              destination:
                type: string

            required:
              - path

        Annotation:
          type: array
          minItems: 1

          items:
            type: object

            properties:
              path:
                $ref: '#/components/schemas/UserHomePath'

              destination:
                type: string

            required:
              - path

      required:
        - Sequence
        - Annotation

    TradViaFileFormDataSequence:
      allOf:
        - oneOf:
          - type: object

            properties:
              Sequence[][file]:
                type: array
                minItems: 1

                items:
                  type: string
                  format: binary

            required:
              - Sequence[][file]

          - type: object

            properties:
              Sequence[][path]:
                type: array
                minItems: 1

                items:
                  $ref: '#/components/schemas/UserHomePath'

            required:
              - Sequence[][path]

        - type: object

          properties:
            Sequence[][destination]:
              type: array
              minItems: 1

              items:
                type: string

    TradViaFileFormDataAnnotation:
      allOf:
        - oneOf:
          - type: object

            properties:
              Annotation[][file]:
                type: array
                minItems: 1

                items:
                  type: string
                  format: binary

            required:
              - Annotation[][file]

          - type: object

            properties:
              Annotation[][path]:
                type: array
                minItems: 1

                items:
                  $ref: '#/components/schemas/UserHomePath'

            required:
              - Annotation[][path]

        - type: object

          properties:
            Annotation[][destination]:
              type: array
              minItems: 1

              items:
                type: string

    DRAViaFileJSON:
      type: object

      properties:
        Submission:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        Experiment:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        Run:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        RunFile:
          type: array
          minItems: 1

          items:
            type: object

            properties:
              path:
                $ref: '#/components/schemas/UserHomePath'

              destination:
                type: string

            required:
              - path

        Analysis:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        AnalysisFile:
          type: array
          minItems: 0

          items:
            type: object

            properties:
              path:
                $ref: '#/components/schemas/UserHomePath'

              destination:
                type: string

            required:
              - path

      required:
        - Submission
        - Experiment
        - Run
        - RunFile

    DRAViaFileFormDataSubmission:
      allOf:
        - oneOf:
          - type: object

            properties:
              Submission[file]:
                type: string
                format: binary

            required:
              - Submission[file]

          - type: object

            properties:
              Submission[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - Submission[path]

        - type: object

          properties:
            Submission[destination]:
              type: string

    DRAViaFileFormDataExperiment:
      allOf:
        - oneOf:
          - type: object

            properties:
              Experiment[file]:
                type: string
                format: binary

            required:
              - Experiment[file]

          - type: object

            properties:
              Experiment[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - Experiment[path]

        - type: object

          properties:
            Experiment[destination]:
              type: string

    DRAViaFileFormDataRun:
      allOf:
        - oneOf:
          - type: object

            properties:
              Run[file]:
                type: string
                format: binary

            required:
              - Run[file]

          - type: object

            properties:
              Run[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - Run[path]

        - type: object

          properties:
            Run[destination]:
              type: string

    DRAViaFileFormDataRunFile:
      allOf:
        - oneOf:
          - type: object

            properties:
              RunFile[][file]:
                type: array
                minItems: 1

                items:
                  type: string
                  format: binary

            required:
              - RunFile[][file]

          - type: object

            properties:
              RunFile[][path]:
                type: array
                minItems: 1

                items:
                  $ref: '#/components/schemas/UserHomePath'

            required:
              - RunFile[][path]

        - type: object

          properties:
            RunFile[][destination]:
              type: array
              minItems: 1

              items:
                type: string

    DRAViaFileFormDataAnalysis:
      allOf:
        - oneOf:
          - type: object

            properties:
              Analysis[file]:
                type: string
                format: binary

          - type: object

            properties:
              Analysis[path]:
                $ref: '#/components/schemas/UserHomePath'

        - type: object

          properties:
            Analysis[destination]:
              type: string

    DRAViaFileFormDataAnalysisFile:
      allOf:
        - oneOf:
          - type: object

            properties:
              AnalysisFile[][file]:
                type: array
                minItems: 0

                items:
                  type: string
                  format: binary

          - type: object

            properties:
              AnalysisFile[][path]:
                type: array
                minItems: 0

                items:
                  $ref: '#/components/schemas/UserHomePath'

        - type: object

          properties:
            AnalysisFile[][destination]:
              type: array
              minItems: 0

              items:
                type: string

    GEAViaFileJSON:
      type: object

      properties:
        IDF:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        SDRF:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        ADF:
          type: array
          minItems: 0

          items:
            type: object

            properties:
              path:
                $ref: '#/components/schemas/UserHomePath'

              destination:
                type: string

            required:
              - path

        RawDataFile:
          type: array
          minItems: 0

          items:
            type: object

            properties:
              path:
                $ref: '#/components/schemas/UserHomePath'

              destination:
                type: string

            required:
              - path

        ProcessedDataFile:
          type: array
          minItems: 0

          items:
            type: object

            properties:
              path:
                $ref: '#/components/schemas/UserHomePath'

              destination:
                type: string

            required:
              - path

      required:
        - IDF
        - SDRF

    GEAViaFileFormDataIDF:
      allOf:
        - oneOf:
          - type: object

            properties:
              IDF[file]:
                type: string
                format: binary

            required:
              - IDF[file]

          - type: object

            properties:
              IDF[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - IDF[path]

        - type: object

          properties:
            IDF[destination]:
              type: string

    GEAViaFileFormDataSDRF:
      allOf:
        - oneOf:
          - type: object

            properties:
              SDRF[file]:
                type: string
                format: binary

            required:
              - SDRF[file]

          - type: object

            properties:
              SDRF[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - SDRF[path]

        - type: object

          properties:
            SDRF[destination]:
              type: string

    GEAViaFileFormDataADF:
      allOf:
        - oneOf:
          - type: object

            properties:
              ADF[][file]:
                type: array
                minItems: 0

                items:
                  type: string
                  format: binary

          - type: object

            properties:
              ADF[][path]:
                type: array
                minItems: 0

                items:
                  $ref: '#/components/schemas/UserHomePath'

        - type: object

          properties:
            ADF[][destination]:
              type: array
              minItems: 0

              items:
                type: string

    GEAViaFileFormDataRawDataFile:
      allOf:
        - oneOf:
          - type: object

            properties:
              RawDataFile[][file]:
                type: array
                minItems: 0

                items:
                  type: string
                  format: binary

          - type: object

            properties:
              RawDataFile[][path]:
                type: array
                minItems: 0

                items:
                  $ref: '#/components/schemas/UserHomePath'

        - type: object

          properties:
            RawDataFile[][destination]:
              type: array
              minItems: 0

              items:
                type: string

    GEAViaFileFormDataProcessedDataFile:
      allOf:
        - oneOf:
          - type: object

            properties:
              ProcessedDataFile[][file]:
                type: array
                minItems: 0

                items:
                  type: string
                  format: binary

          - type: object

            properties:
              ProcessedDataFile[][path]:
                type: array
                minItems: 0

                items:
                  $ref: '#/components/schemas/UserHomePath'

        - type: object

          properties:
            ProcessedDataFile[][destination]:
              type: array
              minItems: 0

              items:
                type: string

    MetaboBankViaFileJSON:
      type: object

      properties:
        IDF:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        SDRF:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        MAF:
          type: array
          minItems: 0

          items:
            type: object

            properties:
              path:
                $ref: '#/components/schemas/UserHomePath'

              destination:
                type: string

            required:
              - path

        RawDataFile:
          type: array
          minItems: 0

          items:
            type: object

            properties:
              path:
                $ref: '#/components/schemas/UserHomePath'

              destination:
                type: string

            required:
              - path

        ProcessedDataFile:
          type: array
          minItems: 0

          items:
            type: object

            properties:
              path:
                $ref: '#/components/schemas/UserHomePath'

              destination:
                type: string

            required:
              - path

        BioSample:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

      required:
        - IDF
        - SDRF

    MetaboBankViaFileFormDataIDF:
      allOf:
        - oneOf:
          - type: object

            properties:
              IDF[file]:
                type: string
                format: binary

            required:
              - IDF[file]

          - type: object

            properties:
              IDF[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - IDF[path]

        - type: object

          properties:
            IDF[destination]:
              type: string

    MetaboBankViaFileFormDataSDRF:
      allOf:
        - oneOf:
          - type: object

            properties:
              SDRF[file]:
                type: string
                format: binary

            required:
              - SDRF[file]

          - type: object

            properties:
              SDRF[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - SDRF[path]

        - type: object

          properties:
            SDRF[destination]:
              type: string

    MetaboBankViaFileFormDataMAF:
      allOf:
        - oneOf:
          - type: object

            properties:
              MAF[][file]:
                type: array
                minItems: 0

                items:
                  type: string
                  format: binary

          - type: object

            properties:
              MAF[][path]:
                type: array
                minItems: 0

                items:
                  $ref: '#/components/schemas/UserHomePath'

        - type: object

          properties:
            MAF[][destination]:
              type: array
              minItems: 0

              items:
                type: string

    MetaboBankViaFileFormDataRawDataFile:
      allOf:
        - oneOf:
          - type: object

            properties:
              RawDataFile[][file]:
                type: array
                minItems: 0

                items:
                  type: string
                  format: binary

          - type: object

            properties:
              RawDataFile[][path]:
                type: array
                minItems: 0

                items:
                  $ref: '#/components/schemas/UserHomePath'

        - type: object

          properties:
            RawDataFile[][destination]:
              type: array
              minItems: 0

              items:
                type: string

    MetaboBankViaFileFormDataProcessedDataFile:
      allOf:
        - oneOf:
          - type: object

            properties:
              ProcessedDataFile[][file]:
                type: array
                minItems: 0

                items:
                  type: string
                  format: binary

          - type: object

            properties:
              ProcessedDataFile[][path]:
                type: array
                minItems: 0

                items:
                  $ref: '#/components/schemas/UserHomePath'

        - type: object

          properties:
            ProcessedDataFile[][destination]:
              type: array
              minItems: 0

              items:
                type: string

    MetaboBankViaFileFormDataBioSample:
      allOf:
        - oneOf:
          - type: object

            properties:
              BioSample[file]:
                type: string
                format: binary

          - type: object

            properties:
              BioSample[path]:
                $ref: '#/components/schemas/UserHomePath'

        - type: object

          properties:
            BioSample[destination]:
              type: string

    JVarViaFileJSON:
      type: object

      properties:
        Study:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        SampleSet:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        Sample:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        Experiment:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        Assay:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        VariantCallSV:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        VariantRegionSV:
          type: object

          properties:
            path:
              $ref: '#/components/schemas/UserHomePath'

            destination:
              type: string

          required:
            - path

        VariantCallFile:
          type: array
          minItems: 0

          items:
            type: object

            properties:
              path:
                $ref: '#/components/schemas/UserHomePath'

              destination:
                type: string

            required:
              - path

      required:
        - Study
        - SampleSet
        - Sample
        - Experiment
        - Assay
        - VariantCallSV
        - VariantRegionSV

    JVarViaFileFormDataStudy:
      allOf:
        - oneOf:
          - type: object

            properties:
              Study[file]:
                type: string
                format: binary

            required:
              - Study[file]

          - type: object

            properties:
              Study[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - Study[path]

        - type: object

          properties:
            Study[destination]:
              type: string

    JVarViaFileFormDataSampleSet:
      allOf:
        - oneOf:
          - type: object

            properties:
              SampleSet[file]:
                type: string
                format: binary

            required:
              - SampleSet[file]

          - type: object

            properties:
              SampleSet[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - SampleSet[path]

        - type: object

          properties:
            SampleSet[destination]:
              type: string

    JVarViaFileFormDataSample:
      allOf:
        - oneOf:
          - type: object

            properties:
              Sample[file]:
                type: string
                format: binary

            required:
              - Sample[file]

          - type: object

            properties:
              Sample[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - Sample[path]

        - type: object

          properties:
            Sample[destination]:
              type: string

    JVarViaFileFormDataExperiment:
      allOf:
        - oneOf:
          - type: object

            properties:
              Experiment[file]:
                type: string
                format: binary

            required:
              - Experiment[file]

          - type: object

            properties:
              Experiment[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - Experiment[path]

        - type: object

          properties:
            Experiment[destination]:
              type: string

    JVarViaFileFormDataAssay:
      allOf:
        - oneOf:
          - type: object

            properties:
              Assay[file]:
                type: string
                format: binary

            required:
              - Assay[file]

          - type: object

            properties:
              Assay[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - Assay[path]

        - type: object

          properties:
            Assay[destination]:
              type: string

    JVarViaFileFormDataVariantCallSV:
      allOf:
        - oneOf:
          - type: object

            properties:
              VariantCallSV[file]:
                type: string
                format: binary

            required:
              - VariantCallSV[file]

          - type: object

            properties:
              VariantCallSV[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - VariantCallSV[path]

        - type: object

          properties:
            VariantCallSV[destination]:
              type: string

    JVarViaFileFormDataVariantRegionSV:
      allOf:
        - oneOf:
          - type: object

            properties:
              VariantRegionSV[file]:
                type: string
                format: binary

            required:
              - VariantRegionSV[file]

          - type: object

            properties:
              VariantRegionSV[path]:
                $ref: '#/components/schemas/UserHomePath'

            required:
              - VariantRegionSV[path]

        - type: object

          properties:
            VariantRegionSV[destination]:
              type: string

    JVarViaFileFormDataVariantCallFile:
      allOf:
        - oneOf:
          - type: object

            properties:
              VariantCallFile[][file]:
                type: array
                minItems: 0

                items:
                  type: string
                  format: binary

          - type: object

            properties:
              VariantCallFile[][path]:
                type: array
                minItems: 0

                items:
                  $ref: '#/components/schemas/UserHomePath'

        - type: object

          properties:
            VariantCallFile[][destination]:
              type: array
              minItems: 0

              items:
                type: string

    UserHomePath:
      type: string
      description: Relative path from the user's home directory.

  requestBodies:
    BioProjectViaFile:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BioProjectViaFileJSON'

          example:
            BioProject:
              path: mybioproject.xml
              destination: path/to/destination

        multipart/form-data:
          schema:
            allOf:
              - $ref: '#/components/schemas/BioProjectViaFileFormDataBioProject'

    BioSampleViaFile:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BioSampleViaFileJSON'

          example:
            BioSample:
              path: mybiosample.xml
              destination: path/to/destination

        multipart/form-data:
          schema:
            allOf:
              - $ref: '#/components/schemas/BioSampleViaFileFormDataBioSample'

    TradViaFile:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TradViaFileJSON'

          example:
            Sequence:
              path: mysequence.fasta
              destination: path/to/destination
            Annotation:
              path: myannotation.ann
              destination: path/to/destination

        multipart/form-data:
          schema:
            allOf:
              - $ref: '#/components/schemas/TradViaFileFormDataSequence'
              - $ref: '#/components/schemas/TradViaFileFormDataAnnotation'

    DRAViaFile:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DRAViaFileJSON'

          example:
            Submission:
              path: mysubmission.xml
              destination: path/to/destination
            Experiment:
              path: myexperiment.xml
              destination: path/to/destination
            Run:
              path: myrun.xml
              destination: path/to/destination
            RunFile:
              path: myrunfile.fastq
              destination: path/to/destination
            Analysis:
              path: myanalysis.xml
              destination: path/to/destination
            AnalysisFile:
              path: myanalysisfile.raw
              destination: path/to/destination

        multipart/form-data:
          schema:
            allOf:
              - $ref: '#/components/schemas/DRAViaFileFormDataSubmission'
              - $ref: '#/components/schemas/DRAViaFileFormDataExperiment'
              - $ref: '#/components/schemas/DRAViaFileFormDataRun'
              - $ref: '#/components/schemas/DRAViaFileFormDataRunFile'
              - $ref: '#/components/schemas/DRAViaFileFormDataAnalysis'
              - $ref: '#/components/schemas/DRAViaFileFormDataAnalysisFile'

    GEAViaFile:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GEAViaFileJSON'

          example:
            IDF:
              path: myidf.idf.txt
              destination: path/to/destination
            SDRF:
              path: mysdrf.sdrf.txt
              destination: path/to/destination
            ADF:
              path: myadf.adf.txt
              destination: path/to/destination
            RawDataFile:
              path: myrawdatafile.raw
              destination: path/to/destination
            ProcessedDataFile:
              path: myprocesseddatafile.raw
              destination: path/to/destination

        multipart/form-data:
          schema:
            allOf:
              - $ref: '#/components/schemas/GEAViaFileFormDataIDF'
              - $ref: '#/components/schemas/GEAViaFileFormDataSDRF'
              - $ref: '#/components/schemas/GEAViaFileFormDataADF'
              - $ref: '#/components/schemas/GEAViaFileFormDataRawDataFile'
              - $ref: '#/components/schemas/GEAViaFileFormDataProcessedDataFile'

    MetaboBankViaFile:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MetaboBankViaFileJSON'

          example:
            IDF:
              path: myidf.idf.txt
              destination: path/to/destination
            SDRF:
              path: mysdrf.sdrf.txt
              destination: path/to/destination
            MAF:
              path: mymaf.maf.txt
              destination: path/to/destination
            RawDataFile:
              path: myrawdatafile.raw
              destination: path/to/destination
            ProcessedDataFile:
              path: myprocesseddatafile.raw
              destination: path/to/destination
            BioSample:
              path: mybiosample.tsv
              destination: path/to/destination

        multipart/form-data:
          schema:
            allOf:
              - $ref: '#/components/schemas/MetaboBankViaFileFormDataIDF'
              - $ref: '#/components/schemas/MetaboBankViaFileFormDataSDRF'
              - $ref: '#/components/schemas/MetaboBankViaFileFormDataMAF'
              - $ref: '#/components/schemas/MetaboBankViaFileFormDataRawDataFile'
              - $ref: '#/components/schemas/MetaboBankViaFileFormDataProcessedDataFile'
              - $ref: '#/components/schemas/MetaboBankViaFileFormDataBioSample'

    JVarViaFile:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/JVarViaFileJSON'

          example:
            Study:
              path: mystudy.tsv
              destination: path/to/destination
            SampleSet:
              path: mysampleset.tsv
              destination: path/to/destination
            Sample:
              path: mysample.tsv
              destination: path/to/destination
            Experiment:
              path: myexperiment.tsv
              destination: path/to/destination
            Assay:
              path: myassay.tsv
              destination: path/to/destination
            VariantCallSV:
              path: myvariantcallsv.tsv
              destination: path/to/destination
            VariantRegionSV:
              path: myvariantregionsv.tsv
              destination: path/to/destination
            VariantCallFile:
              path: myvariantcallfile.vcf
              destination: path/to/destination

        multipart/form-data:
          schema:
            allOf:
              - $ref: '#/components/schemas/JVarViaFileFormDataStudy'
              - $ref: '#/components/schemas/JVarViaFileFormDataSampleSet'
              - $ref: '#/components/schemas/JVarViaFileFormDataSample'
              - $ref: '#/components/schemas/JVarViaFileFormDataExperiment'
              - $ref: '#/components/schemas/JVarViaFileFormDataAssay'
              - $ref: '#/components/schemas/JVarViaFileFormDataVariantCallSV'
              - $ref: '#/components/schemas/JVarViaFileFormDataVariantRegionSV'
              - $ref: '#/components/schemas/JVarViaFileFormDataVariantCallFile'

  responses:
    CreateResponseCreated:
      description: The requested process initiated successfully.

      content:
        application/json:
          schema:
            type: object

            properties:
              request:
                type: object

                properties:
                  id:
                    type: integer

                  url:
                    type: string
                    format: uri

                required:
                  - id
                  - url

            required:
              - request

          example:
            request:
              id: 42
              url: http://www.example.com/api/requests/42

    CreateResponseBadRequest:
      description: The requested process could not be initiated.

      content:
        application/json:
          schema:
            type: object

            properties:
              error:
                type: string

            required:
              - error

          example:
            error: path must be in /home/alice
